### PR TITLE
Avcodec freeworld

### PR DESCRIPTION
**Pull request by kwizart**

### CODE REVIEW

**Comment by leigh123linux** [comment]
I'm unable to test as my installed packages require ffmpeg-libs.

**Comment by kwizart** [comment]
I plan to push this newer revision for f37+

**Comment by leigh123linux** [comment]
> I plan to push this newer revision for f37+

Please don't as fedora ffmpeg isn't in sync https://koji.fedoraproject.org/koji/buildinfo?buildID=2057469

**Comment by kwizart** [comment]
Well, this is the fundamental reason why I said originally that a complementary ffmpeg should be a separate package.

I'm thinking about only pushing the reverts for now. (then see what we can have in f37 GA in 0 day updates).

libavcodec-freeworld package doesn't yet need any strong version dependencies over the fedora counterpart.

**Comment by sergiomb2** [comment]
> a complementary ffmpeg should be a separate package.

@kwizart only libavcodec_freeworld is need to complement ffmpeg-free ?

**Comment by kwizart** [comment]
> > a complementary ffmpeg should be a separate package.
> 
> @kwizart only libavcodec_freeworld is need to complement ffmpeg-free ?

Sure, nothing uses x264.h/x265.h elsewhere from libavcodec

**Comment by rathann** [comment]
I tested this on F37 and it seems to work fine. Thanks, @kwizart .

**Comment by runlevel5** [comment]
Tested today with F37. It works fine :+1:

**Comment by kwizart** [comment]
Merged earlier.

**Pull request closed without merging**
